time: 1
distance: 10
npc:
  대지주 토마스: 0:76:1010:ReWorld
  농장 관리부 잭: -79:65:1079:ReWorld
  풍차지기 헬렌: 65.1943:65:1103:ReWorld
  톰슨 할아버지: 1:86:988:ReWorld
  창고 지킴이 벙크: -60:66:1061:ReWorld
  제 1 기사단장 아스트라: 294:73:56:ReWorld
  제 2 기사단장 프론: -92:65:325:ReWorld
  밀수 상인 브리트: 53:65:284:ReWorld
  검은 로브를 쓴 남자: -123:40:436:ReWorld
place:
  토마스의 대저택: 0.5:76:1000.5:ReWorld
  토마스의 농장: -40:65:1308.5:ReWorld
  켄텀브리엄: 0.5:76:5.5:ReWorld
  켄텀브리엄 상점가: 33.5:66:-274.5:ReWorld
  산적 근거지: 424.5:65:100.5:ReWorld
  프렐교 근거지: -30.5:66:456.5:ReWorld
  해적 근거지: 365:65:-867:ReWorld
  저주받은 광산: 787:65:-19.5:ReWorld
  척박한 사막: -366.5:66:-1195.5:ReWorld
  얼어붇은 호수: -999.5:64:-538.5:ReWorld
  똘이마을 다리: 1003.5:99:780.5:ReWorld
  똘이마을 입구: 832.5:70:871:ReWorld
  #파괴된 도시
  대신전: -110.5:65:-614.5:ReWorld
